theme: jekyll-theme-cayman
title: Mobile Swipe Menu
show_downloads: true
github:
  zip_url: https://github.com/milkamil93/mobile-swipe-menu/zipball/master
  tar_url: https://github.com/milkamil93/mobile-swipe-menu/tarball/master